<?php
use Drupal\file\Entity\File;
use Drupal\image\Entity\ImageStyle;
use Drupal\Core\Form\FormStateInterface;
use Drupal\views\ViewExecutable;
use Drupal\taxonomy\Entity\Term;
use Drupal\views\Plugin\views\query\QueryPluginBase;
use Drupal\Core\Url;
use Drupal\Core\Link;
function d8_utility_theme() {
    return [
        'page_statistique' => array(
            'variables' => array('data' => NULL),
        ),
    ];
}
/**
 * Implements template_preprocess_views_view_field().
 */
function d8_utility_preprocess_views_view_field(&$variables)
{
  $view = $variables['view'];
  $field = $variables['field'];

  if ($view->current_display == 'liste_statistique') {
    $entity = $variables["row"]->_entity;
    switch($field->field)
    {
      case 'nothing':
        $result =  array(
          '#markup' => '<a href="/statistique/'.$entity->id().'/'.$entity->field_annee_scolaire->value.'" target="_blank">Voir</a>',
        );
        $renderer = \Drupal::service('renderer');
        $html = $renderer->render($result);
        $variables['output'] = $html;
        break;
    }
  }
  if ($view->current_display == 'liste_sandages_pour_etudiant') {
    $entity = $variables["row"]->_entity;
    if ($field->field == 'operations'){
      $result =  array(
        '#markup' => '<a href="/sondage-de-satisfaction-des-etudiants-universitaires/'.$entity->id().'">Remplir le questionnaire</a>',
      );
      $renderer = \Drupal::service('renderer');
      $html = $renderer->render($result);
      $variables['output'] = $html;
    }elseif ($field->field == 'nothing'){
        $class = get_status($entity->id());
      $result =  array(
        '#markup' => '<span class="'.$class.'">img</span>',
      );
      $renderer = \Drupal::service('renderer');
      $html = $renderer->render($result);
      $variables['output'] = $html;
    }
  }
}
function get_status($id)
    {
        $uid = \Drupal::currentUser()->id();
    
        $query = \Drupal::entityQuery('node');
        $query->condition('status', 1);
        $query->condition('type', 'reponses');
        $query->condition('uid', $uid);
        $query->condition('field_sondage', $id);
        $entity_ids = $query->execute();
        if ($entity_ids) {
            return "valide";
        }
        return "non-valide";
    }
